<?php

declare(strict_types=1);

namespace Watchtower\Agent\Console;

use Illuminate\Console\Command;
use RuntimeException;

class TestExceptionCommand extends Command
{
    protected $signature = 'watchtower:test-exception {--no-flush : Buffer the exception without flushing to the hub}';

    protected $description = 'Report a synthetic exception to verify it reaches the Watchtower hub';

    public function handle(): int
    {
        if (! (bool) config('watchtower.enabled', true)) {
            $this->warn('Watchtower is disabled (WATCHTOWER_ENABLED=false); the exception will not be captured.');
        }

        if (! (bool) config('watchtower.features.exceptions', true)) {
            $this->warn('Exception capture is off (watchtower.features.exceptions=false); nothing will be reported.');
        }

        report(new RuntimeException('Watchtower test exception generated by watchtower:test-exception at '.date('c')));

        $this->info('Reported a synthetic exception to the Watchtower agent.');

        if ($this->option('no-flush')) {
            $this->comment('Buffered only; it will be sent on the next scheduled flush.');

            return self::SUCCESS;
        }

        $this->comment('Flushing to the hub...');
        $this->call('watchtower:flush');
        $this->info("Done. Check the site's Exceptions tab on the hub.");

        return self::SUCCESS;
    }
}
